import type { ToolDefinition, Category } from '@/lib/types';

/**
 * Master tool registry. Each entry defines a tool's metadata, computation reference,
 * content, SEO, and relationships. Adding a new tool means adding an entry here.
 */

export const tools: ToolDefinition[] = [
  // ===== MATH =====
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    category: 'math',
    title: 'Percentage Calculator',
    shortDescription: 'Calculate what is X% of Y, or what percent X is of Y.',
    keywords: ['percentage', 'percent', 'of', 'what is x percent of y', 'percent of'],
    aliases: ['percent calculator', 'x percent of y'],
    computation: 'percentageOf',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Result = (Percentage / 100) × Value',
    explanation:
      'This calculator finds a percentage of a number. Enter the percentage and the value you want to take the percentage of. For example, 15% of 200 is (15/100) × 200 = 30.',
    examples: [
      { title: 'Basic percentage', inputs: [{ label: 'Percentage', value: '15%' }, { label: 'Value', value: '200' }], result: '15% of 200 = 30' },
    ],
    assumptions: 'Results are rounded to 2 decimal places.',
    relatedTools: ['percentage-increase-calculator', 'percentage-decrease-calculator', 'percentage-difference-calculator', 'percentage-change-calculator', 'discount-calculator', 'fraction-to-percentage'],
    faq: [
      { question: 'What is a percentage?', answer: 'A percentage expresses a number as a fraction of 100. 50% means 50 out of 100, or half.' },
      { question: 'How do I calculate a percentage of a number?', answer: 'Convert the percentage to a decimal (divide by 100) and multiply by the number. For 20% of 80: 0.20 × 80 = 16.' },
    ],
    ogImage: '/og/percentage-calculator.png',
  },
  {
    id: 'percentage-increase-calculator',
    slug: 'percentage-increase-calculator',
    category: 'math',
    title: 'Percentage Increase Calculator',
    shortDescription: 'Calculate the percentage increase from an original value to a new value.',
    keywords: ['percentage increase', 'percent increase', 'increase percentage', 'growth rate'],
    aliases: ['percent increase calculator', 'increase percentage calculator'],
    computation: 'percentageIncrease',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage Increase = ((New Value − Original Value) / |Original Value|) × 100',
    explanation:
      'The percentage increase measures how much a value has grown relative to its original value. A positive result means the value increased; the formula uses the absolute value of the original to handle negative starting values correctly.',
    examples: [
      { title: 'Price increase', inputs: [{ label: 'Original', value: '$50' }, { label: 'New', value: '$65' }], result: 'Increase = ((65 − 50) / 50) × 100 = 30%' },
    ],
    assumptions: 'The original value must not be zero.',
    relatedTools: ['percentage-decrease-calculator', 'percentage-change-calculator', 'percentage-difference-calculator', 'percentage-calculator', 'discount-calculator'],
    faq: [
      { question: 'What if the original value is zero?', answer: 'Percentage increase is undefined when the original value is zero, because you cannot divide by zero. The calculator will show an error.' },
      { question: 'Can the result be negative?', answer: 'If the new value is lower than the original, the result is negative, indicating a decrease rather than an increase. Use the Percentage Decrease Calculator for that scenario.' },
    ],
  },
  {
    id: 'percentage-decrease-calculator',
    slug: 'percentage-decrease-calculator',
    category: 'math',
    title: 'Percentage Decrease Calculator',
    shortDescription: 'Calculate the percentage decrease from an original value to a new value.',
    keywords: ['percentage decrease', 'percent decrease', 'decrease percentage', 'decline rate'],
    aliases: ['percent decrease calculator', 'decrease percentage calculator'],
    computation: 'percentageDecrease',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage Decrease = ((Original Value − New Value) / |Original Value|) × 100',
    explanation:
      'The percentage decrease measures how much a value has dropped relative to its original value. A positive result means the value decreased. If the new value is higher than the original, the result will be negative.',
    examples: [
      { title: 'Price drop', inputs: [{ label: 'Original', value: '$80' }, { label: 'New', value: '$60' }], result: 'Decrease = ((80 − 60) / 80) × 100 = 25%' },
    ],
    assumptions: 'The original value must not be zero.',
    relatedTools: ['percentage-increase-calculator', 'percentage-change-calculator', 'percentage-difference-calculator', 'percentage-calculator', 'discount-calculator'],
  },
  {
    id: 'percentage-difference-calculator',
    slug: 'percentage-difference-calculator',
    category: 'math',
    title: 'Percentage Difference Calculator',
    shortDescription: 'Calculate the percentage difference between two values using their average.',
    keywords: ['percentage difference', 'percent difference', 'difference between two numbers percentage'],
    aliases: ['percent difference calculator'],
    computation: 'percentageDifference',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage Difference = (|Value A − Value B| / ((Value A + Value B) / 2)) × 100',
    explanation:
      'Percentage difference compares two values without designating one as the "original." It divides the absolute difference by the average of the two values. This is useful when comparing two measurements of the same thing where neither is a baseline.',
    examples: [
      { title: 'Comparing two measurements', inputs: [{ label: 'Value A', value: '120' }, { label: 'Value B', value: '100' }], result: 'Difference = (|120 − 100| / 110) × 100 ≈ 18.18%' },
    ],
    assumptions: 'The average of the two values must not be zero.',
    relatedTools: ['percentage-change-calculator', 'percentage-increase-calculator', 'percentage-decrease-calculator', 'percentage-calculator'],
    faq: [
      { question: 'What is the difference between percentage difference and percentage change?', answer: 'Percentage change uses one value as the baseline (the "original"), while percentage difference treats both values equally by using their average as the denominator.' },
    ],
  },
  {
    id: 'percentage-change-calculator',
    slug: 'percentage-change-calculator',
    category: 'math',
    title: 'Percentage Change Calculator',
    shortDescription: 'Calculate the percentage change between two values, showing increase or decrease.',
    keywords: ['percentage change', 'percent change', 'change percentage', 'relative change'],
    aliases: ['percent change calculator'],
    computation: 'percentageChange',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage Change = ((New Value − Original Value) / |Original Value|) × 100',
    explanation:
      'Percentage change shows how much a value changed relative to its original, with the sign indicating direction: positive for increase, negative for decrease. It is the general form of both the percentage increase and percentage decrease formulas.',
    examples: [
      { title: 'Stock price change', inputs: [{ label: 'Original', value: '$120' }, { label: 'New', value: '$150' }], result: 'Change = ((150 − 120) / 120) × 100 = +25%' },
    ],
    assumptions: 'The original value must not be zero.',
    relatedTools: ['percentage-increase-calculator', 'percentage-decrease-calculator', 'percentage-difference-calculator', 'percentage-calculator'],
  },
  {
    id: 'fraction-calculator',
    slug: 'fraction-calculator',
    category: 'math',
    title: 'Fraction Calculator',
    shortDescription: 'Add, subtract, multiply, or divide two fractions and get a simplified result.',
    keywords: ['fraction calculator', 'add fractions', 'subtract fractions', 'multiply fractions', 'divide fractions'],
    aliases: ['fraction add subtract multiply divide'],
    computation: 'fractionOp',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Operations use common denominators for add/subtract and cross-multiplication for multiply/divide, then simplify by GCD.',
    explanation:
      'This calculator performs arithmetic on two fractions. For addition and subtraction, it finds a common denominator. For multiplication and division, it multiplies or cross-multiplies the numerators and denominators. The result is simplified by dividing both parts by their greatest common divisor.',
    examples: [
      { title: 'Add fractions', inputs: [{ label: 'Fraction 1', value: '1/2' }, { label: 'Fraction 2', value: '1/3' }], result: '1/2 + 1/3 = 3/6 + 2/6 = 5/6' },
    ],
    assumptions: 'Denominators must not be zero.',
    relatedTools: ['fraction-to-decimal', 'decimal-to-fraction', 'fraction-to-percentage', 'percentage-calculator'],
  },
  {
    id: 'fraction-to-decimal',
    slug: 'fraction-to-decimal',
    category: 'math',
    title: 'Fraction to Decimal Calculator',
    shortDescription: 'Convert any fraction to its decimal equivalent.',
    keywords: ['fraction to decimal', 'convert fraction to decimal', 'fraction decimal'],
    aliases: ['fraction to decimal converter'],
    computation: 'fractionToDecimal',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Decimal = Numerator ÷ Denominator',
    explanation: 'Divide the numerator by the denominator to get the decimal equivalent. The result is shown with up to 10 decimal places.',
    examples: [{ title: 'Basic conversion', inputs: [{ label: '3/4' }], result: '3 ÷ 4 = 0.75' }],
    assumptions: 'The denominator must not be zero.',
    relatedTools: ['decimal-to-fraction', 'fraction-to-percentage', 'fraction-calculator', 'percentage-calculator'],
  },
  {
    id: 'decimal-to-fraction',
    slug: 'decimal-to-fraction',
    category: 'math',
    title: 'Decimal to Fraction Calculator',
    shortDescription: 'Convert a decimal number to its simplest fraction form.',
    keywords: ['decimal to fraction', 'convert decimal to fraction', 'decimal fraction'],
    aliases: ['decimal to fraction converter'],
    computation: 'decimalToFraction',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses continued fraction approximation to find the closest rational number, then simplifies by GCD.',
    explanation: 'This calculator converts a decimal to a fraction by finding the closest rational approximation using continued fractions, then simplifying it by dividing both the numerator and denominator by their GCD.',
    examples: [{ title: 'Convert 0.75', inputs: [{ label: '0.75' }], result: '0.75 = 3/4' }],
    relatedTools: ['fraction-to-decimal', 'fraction-to-percentage', 'fraction-calculator', 'percentage-calculator'],
  },
  {
    id: 'fraction-to-percentage',
    slug: 'fraction-to-percentage',
    category: 'math',
    title: 'Fraction to Percentage Calculator',
    shortDescription: 'Convert a fraction to a percentage value.',
    keywords: ['fraction to percentage', 'convert fraction to percent', 'fraction percent'],
    aliases: ['fraction to percent converter'],
    computation: 'fractionToPercentage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage = (Numerator ÷ Denominator) × 100',
    explanation: 'Divide the numerator by the denominator and multiply by 100 to get the percentage.',
    examples: [{ title: 'Convert 3/4', inputs: [{ label: '3/4' }], result: '(3 ÷ 4) × 100 = 75%' }],
    assumptions: 'The denominator must not be zero.',
    relatedTools: ['percentage-calculator', 'fraction-to-decimal', 'decimal-to-fraction', 'fraction-calculator'],
  },
  {
    id: 'ratio-calculator',
    slug: 'ratio-calculator',
    category: 'math',
    title: 'Ratio Calculator',
    shortDescription: 'Simplify ratios, solve ratio proportions, and scale values.',
    keywords: ['ratio calculator', 'simplify ratio', 'ratio solver', 'proportion ratio'],
    aliases: ['ratio simplifier'],
    computation: 'ratioSimplify',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Simplified ratio = (A ÷ GCD) : (B ÷ GCD)',
    explanation: 'A ratio compares two quantities. To simplify, divide both sides by their greatest common divisor (GCD). The calculator also solves for the missing value in a proportion (A:B = C:D).',
    examples: [{ title: 'Simplify 12:8', inputs: [{ label: '12' }, { label: '8' }], result: 'GCD(12,8)=4 → 3:2' }],
    relatedTools: ['proportion-calculator', 'percentage-calculator', 'fraction-calculator'],
  },
  {
    id: 'proportion-calculator',
    slug: 'proportion-calculator',
    category: 'math',
    title: 'Proportion Calculator',
    shortDescription: 'Solve proportions: find the missing value in A/B = C/D.',
    keywords: ['proportion calculator', 'solve proportion', 'cross multiply', 'ratio proportion'],
    aliases: ['proportion solver'],
    computation: 'proportionSolve',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'If A/B = C/D, then D = (B × C) / A (or solve for any missing value)',
    explanation: 'A proportion states that two ratios are equal. Using cross-multiplication, if three values are known, the fourth can be found.',
    examples: [{ title: 'Find D', inputs: [{ label: 'A=3' }, { label: 'B=6' }, { label: 'C=5' }, { label: 'D=?' }], result: 'D = (6×5)/3 = 10' }],
    relatedTools: ['ratio-calculator', 'percentage-calculator', 'fraction-calculator'],
  },
  {
    id: 'average-calculator',
    slug: 'average-calculator',
    category: 'math',
    title: 'Average Calculator',
    shortDescription: 'Calculate the arithmetic mean of any set of numbers.',
    keywords: ['average calculator', 'mean calculator', 'arithmetic mean', 'find average'],
    aliases: ['mean calculator'],
    computation: 'average',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Average = Sum of all values ÷ Number of values',
    explanation: 'The arithmetic mean (average) is the sum of all values divided by the count of values. Enter numbers separated by commas or spaces.',
    examples: [{ title: 'Test scores', inputs: [{ label: '85, 90, 78, 92, 88' }], result: 'Sum = 433, Count = 5, Average = 86.6' }],
    relatedTools: ['weighted-average-calculator', 'percentage-calculator', 'ratio-calculator'],
  },
  {
    id: 'weighted-average-calculator',
    slug: 'weighted-average-calculator',
    category: 'math',
    title: 'Weighted Average Calculator',
    shortDescription: 'Calculate the weighted average of values with different weights.',
    keywords: ['weighted average', 'weighted mean', 'average with weights'],
    aliases: ['weighted mean calculator'],
    computation: 'weightedAverage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Weighted Average = Σ(value × weight) ÷ Σ(weight)',
    explanation: 'A weighted average accounts for the relative importance of each value by multiplying it by a weight before summing. The result is divided by the total of all weights.',
    examples: [{ title: 'Course grades', inputs: [{ label: 'Values: 85, 90' }, { label: 'Weights: 3, 2' }], result: '(85×3 + 90×2) / (3+2) = 435/5 = 87' }],
    relatedTools: ['average-calculator', 'percentage-calculator', 'gpa-calculator'],
  },
  {
    id: 'profit-loss-calculator',
    slug: 'profit-loss-calculator',
    category: 'math',
    title: 'Profit/Loss Calculator',
    shortDescription: 'Calculate profit or loss amount and percentage from cost and selling price.',
    keywords: ['profit calculator', 'loss calculator', 'profit loss', 'profit percentage', 'loss percentage'],
    aliases: ['profit and loss calculator'],
    computation: 'profitLoss',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Profit = Selling Price − Cost Price; Profit % = (Profit / Cost Price) × 100',
    explanation: 'Profit is the difference between the selling price and the cost price when the selling price is higher. Loss occurs when the cost price is higher. The percentage is always calculated relative to the cost price.',
    examples: [{ title: 'Selling at profit', inputs: [{ label: 'Cost: $100' }, { label: 'Sell: $150' }], result: 'Profit = $50, Profit % = 50%' }],
    relatedTools: ['discount-calculator', 'percentage-change-calculator', 'percentage-calculator'],
  },
  {
    id: 'discount-calculator',
    slug: 'discount-calculator',
    category: 'math',
    title: 'Discount Calculator',
    shortDescription: 'Calculate the final price after a discount and how much you save.',
    keywords: ['discount calculator', 'sale price', 'percent off', 'discount price', 'savings calculator'],
    aliases: ['percent off calculator', 'sale price calculator'],
    computation: 'discount',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Discount Amount = Original Price × (Discount % / 100); Final Price = Original Price − Discount Amount',
    explanation: 'A discount reduces the original price by a percentage. The discount amount is what you save, and the final price is what you pay.',
    examples: [{ title: '20% off', inputs: [{ label: 'Price: $50' }, { label: 'Discount: 20%' }], result: 'Save $10, Final Price = $40' }],
    relatedTools: ['percentage-calculator', 'profit-loss-calculator', 'percentage-decrease-calculator', 'gst-calculator'],
  },
  {
    id: 'simple-interest-calculator',
    slug: 'simple-interest-calculator',
    category: 'math',
    title: 'Simple Interest Calculator',
    shortDescription: 'Calculate simple interest on a principal amount.',
    keywords: ['simple interest', 'si calculator', 'interest calculator', 'principal interest'],
    aliases: ['si calculator'],
    computation: 'simpleInterest',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Simple Interest = (Principal × Rate × Time) / 100',
    explanation: 'Simple interest is calculated only on the original principal. It does not compound. The rate is per annum and time is in years.',
    examples: [{ title: 'Basic SI', inputs: [{ label: 'P: $1000' }, { label: 'R: 5%' }, { label: 'T: 3 years' }], result: 'SI = (1000 × 5 × 3)/100 = $150' }],
    assumptions: 'Rate is annual and time is in years. No compounding is applied.',
    relatedTools: ['compound-interest-calculator', 'emi-calculator', 'percentage-calculator'],
  },
  {
    id: 'compound-interest-calculator',
    slug: 'compound-interest-calculator',
    category: 'math',
    title: 'Compound Interest Calculator',
    shortDescription: 'Calculate compound interest with customizable compounding frequency.',
    keywords: ['compound interest', 'ci calculator', 'compounding interest', 'interest compounded'],
    aliases: ['ci calculator'],
    computation: 'compoundInterest',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Amount = P × (1 + r/n)^(n×t); CI = Amount − P',
    explanation: 'Compound interest is calculated on the principal plus accumulated interest. The frequency of compounding (n) affects the result: more frequent compounding yields more interest.',
    examples: [{ title: 'Annual compounding', inputs: [{ label: 'P: $1000' }, { label: 'R: 5%' }, { label: 'T: 3 years' }, { label: 'n: 1' }], result: 'Amount = 1000 × (1.05)³ = $1,157.63, CI = $157.63' }],
    assumptions: 'Rate is annual. Time is in years. Compounding frequency is per year.',
    relatedTools: ['simple-interest-calculator', 'emi-calculator', 'sip-calculator', 'fd-calculator'],
  },
  {
    id: 'hcf-calculator',
    slug: 'hcf-calculator',
    category: 'math',
    title: 'HCF Calculator',
    shortDescription: 'Find the Highest Common Factor (GCD) of two or more numbers.',
    keywords: ['hcf', 'gcd', 'highest common factor', 'greatest common divisor'],
    aliases: ['gcd calculator', 'greatest common divisor calculator'],
    computation: 'hcf',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'HCF is found using the Euclidean algorithm: GCD(a, b) = GCD(b, a mod b)',
    explanation: 'The Highest Common Factor (HCF), also called the Greatest Common Divisor (GCD), is the largest number that divides all given numbers without a remainder.',
    examples: [{ title: 'HCF of 12 and 18', inputs: [{ label: '12, 18' }], result: 'GCD(12, 18) = 6' }],
    relatedTools: ['lcm-calculator', 'fraction-calculator', 'ratio-calculator'],
  },
  {
    id: 'lcm-calculator',
    slug: 'lcm-calculator',
    category: 'math',
    title: 'LCM Calculator',
    shortDescription: 'Find the Least Common Multiple of two or more numbers.',
    keywords: ['lcm', 'least common multiple', 'lowest common multiple'],
    aliases: ['least common multiple calculator'],
    computation: 'lcm',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'LCM(a, b) = |a × b| / GCD(a, b)',
    explanation: 'The Least Common Multiple (LCM) is the smallest positive number that is a multiple of all given numbers.',
    examples: [{ title: 'LCM of 4 and 6', inputs: [{ label: '4, 6' }], result: 'LCM(4, 6) = 12' }],
    relatedTools: ['hcf-calculator', 'fraction-calculator', 'ratio-calculator'],
  },
  {
    id: 'permutation-calculator',
    slug: 'permutation-calculator',
    category: 'math',
    title: 'Permutation Calculator',
    shortDescription: 'Calculate the number of permutations: nPr.',
    keywords: ['permutation', 'npr', 'arrangements', 'ordered selection'],
    aliases: ['npr calculator'],
    computation: 'permutation',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'nPr = n! / (n − r)!',
    explanation: 'A permutation counts the number of ways to arrange r items from a set of n items where order matters.',
    examples: [{ title: '5P3', inputs: [{ label: 'n=5' }, { label: 'r=3' }], result: '5!/(5−3)! = 120/2 = 60' }],
    relatedTools: ['combination-calculator', 'probability-calculator', 'factorial'],
  },
  {
    id: 'combination-calculator',
    slug: 'combination-calculator',
    category: 'math',
    title: 'Combination Calculator',
    shortDescription: 'Calculate the number of combinations: nCr.',
    keywords: ['combination', 'ncr', 'selections', 'unordered selection', 'binomial coefficient'],
    aliases: ['ncr calculator'],
    computation: 'combination',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'nCr = n! / (r! × (n − r)!)',
    explanation: 'A combination counts the number of ways to choose r items from a set of n items where order does not matter.',
    examples: [{ title: '5C2', inputs: [{ label: 'n=5' }, { label: 'r=2' }], result: '5!/(2!×3!) = 120/(2×6) = 10' }],
    relatedTools: ['permutation-calculator', 'probability-calculator'],
  },
  {
    id: 'probability-calculator',
    slug: 'probability-calculator',
    category: 'math',
    title: 'Probability Calculator',
    shortDescription: 'Calculate the probability of an event from favorable and total outcomes.',
    keywords: ['probability', 'chance', 'likelihood', 'event probability'],
    aliases: ['probability of event calculator'],
    computation: 'probability',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'P(E) = Favorable Outcomes / Total Outcomes',
    explanation: 'Probability measures how likely an event is to occur. It ranges from 0 (impossible) to 1 (certain). Enter the number of favorable outcomes and total possible outcomes.',
    examples: [{ title: 'Dice roll', inputs: [{ label: 'Favorable: 3' }, { label: 'Total: 6' }], result: 'P = 3/6 = 0.5 or 50%' }],
    relatedTools: ['combination-calculator', 'permutation-calculator', 'percentage-calculator'],
  },
  {
    id: 'speed-distance-time-calculator',
    slug: 'speed-distance-time-calculator',
    category: 'math',
    title: 'Speed, Distance, Time Calculator',
    shortDescription: 'Calculate speed, distance, or time given the other two values.',
    keywords: ['speed calculator', 'distance calculator', 'time calculator', 'speed distance time', 'velocity'],
    aliases: ['speed distance time', 'distance speed time'],
    computation: 'speedDistanceTime',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Speed = Distance / Time; Distance = Speed × Time; Time = Distance / Speed',
    explanation: 'These three quantities are interrelated. Provide any two and the calculator finds the third. Distance is in kilometers, speed in km/h, and time in hours by default.',
    examples: [{ title: 'Find speed', inputs: [{ label: 'Distance: 300 km' }, { label: 'Time: 5 h' }], result: 'Speed = 300/5 = 60 km/h' }],
    relatedTools: ['time-conversion', 'length-conversion', 'fuel-economy-conversion'],
  },
  {
    id: 'time-work-calculator',
    slug: 'time-work-calculator',
    category: 'math',
    title: 'Time and Work Calculator',
    shortDescription: 'Calculate how long a task takes when workers collaborate or work alone.',
    keywords: ['time and work', 'work calculator', 'pipes and cisterns', 'work rate'],
    aliases: ['work time calculator'],
    computation: 'timeWork',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Combined rate = 1/T₁ + 1/T₂; Time together = 1 / Combined rate',
    explanation: 'If a person can complete a task in T₁ days and another in T₂ days, their combined rate is the sum of their individual rates. The time to complete the task together is the reciprocal of the combined rate.',
    examples: [{ title: 'Two workers', inputs: [{ label: 'Worker A: 10 days' }, { label: 'Worker B: 15 days' }], result: 'Combined = 1/10 + 1/15 = 1/6, Time = 6 days' }],
    relatedTools: ['speed-distance-time-calculator', 'average-calculator', 'ratio-calculator'],
  },

  // ===== EVERYDAY =====
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    category: 'everyday',
    title: 'Age Calculator',
    shortDescription: 'Calculate your exact age in years, months, and days from your birth date.',
    keywords: ['age calculator', 'how old am i', 'age from date of birth', 'birthday age'],
    aliases: ['age from birthday', 'date of birth age calculator'],
    computation: 'age',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Age = Reference Date − Birth Date, accounting for month/day boundaries',
    explanation: 'This calculator finds your exact age by counting full years, then remaining months, then remaining days. The calculation accounts for month lengths and leap years.',
    examples: [{ title: 'Age calculation', inputs: [{ label: 'DOB: 1995-03-15' }, { label: 'Reference: 2026-10-07' }], result: '31 years, 6 months, 22 days' }],
    relatedTools: ['date-difference-calculator', 'days-between-dates', 'days-until-date', 'date-add-subtract'],
    faq: [
      { question: 'How is age calculated?', answer: 'Age is counted in completed years, months, and days. If your birthday has not occurred yet this year, one year is subtracted from the difference.' },
    ],
  },
  {
    id: 'date-difference-calculator',
    slug: 'date-difference-calculator',
    category: 'everyday',
    title: 'Date Difference Calculator',
    shortDescription: 'Find the exact difference between two dates in years, months, and days.',
    keywords: ['date difference', 'difference between dates', 'date gap', 'years months days between dates'],
    aliases: ['date difference calculator'],
    computation: 'dateDifference',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Counts full years, then months, then days between the two dates.',
    explanation: 'This calculator measures the time span between two dates, breaking it down into years, months, and days, plus total days and weeks.',
    examples: [{ title: 'Date span', inputs: [{ label: 'From: 2023-01-15' }, { label: 'To: 2026-10-07' }], result: '3 years, 8 months, 22 days' }],
    relatedTools: ['age-calculator', 'days-between-dates', 'date-add-subtract', 'working-days-calculator'],
  },
  {
    id: 'days-between-dates',
    slug: 'days-between-dates',
    category: 'everyday',
    title: 'Days Between Dates Calculator',
    shortDescription: 'Count the exact number of days between two dates.',
    keywords: ['days between dates', 'how many days', 'day counter', 'days from to'],
    aliases: ['days between two dates', 'count days between dates'],
    computation: 'daysBetween',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Days = |Date2 − Date1| in milliseconds / (1000 × 60 × 60 × 24)',
    explanation: 'This calculator counts the total number of days between two dates, including or excluding the end date.',
    examples: [{ title: 'Days count', inputs: [{ label: 'From: 2026-01-01' }, { label: 'To: 2026-12-31' }], result: '364 days (or 365 inclusive)' }],
    relatedTools: ['date-difference-calculator', 'age-calculator', 'working-days-calculator', 'days-until-date'],
  },
  {
    id: 'days-until-date',
    slug: 'days-until-date',
    category: 'everyday',
    title: 'Days Until Calculator',
    shortDescription: 'Count how many days remain until a future date.',
    keywords: ['days until', 'countdown days', 'how many days until', 'days remaining'],
    aliases: ['days until calculator', 'days from now'],
    computation: 'daysUntil',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Days = Target Date − Today (in UTC days)',
    explanation: 'This calculator finds how many days are left until a specific date from today.',
    examples: [{ title: 'Days to New Year', inputs: [{ label: 'Target: 2027-01-01' }], result: 'X days from today' }],
    relatedTools: ['days-between-dates', 'date-difference-calculator', 'date-add-subtract', 'countdown-timer'],
  },
  {
    id: 'date-add-subtract',
    slug: 'date-add-subtract',
    category: 'everyday',
    title: 'Date Add/Subtract Calculator',
    shortDescription: 'Add or subtract days, weeks, months, or years from a date.',
    keywords: ['date add', 'date subtract', 'add days to date', 'add months to date', 'future date'],
    aliases: ['date arithmetic', 'add to date calculator'],
    computation: 'dateAddSub',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Result Date = Start Date ± offset (days, weeks, months, or years)',
    explanation: 'This calculator adds or subtracts a time period from a starting date. Month and year additions handle day-of-month overflow by clamping to the last valid day.',
    examples: [{ title: 'Add 45 days', inputs: [{ label: 'Start: 2026-10-07' }, { label: 'Add: 45 days' }], result: '2026-11-21' }],
    relatedTools: ['days-between-dates', 'days-until-date', 'date-difference-calculator', 'working-days-calculator'],
  },
  {
    id: 'working-days-calculator',
    slug: 'working-days-calculator',
    category: 'everyday',
    title: 'Working Days Calculator',
    shortDescription: 'Count working days (Monday to Friday) between two dates.',
    keywords: ['working days', 'business days', 'working days calculator', 'weekdays between dates'],
    aliases: ['business days calculator'],
    computation: 'workingDays',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Count days that are Monday–Friday between the two dates, excluding weekends.',
    explanation: 'This calculator counts weekdays (Monday through Friday) between two dates. Saturdays and Sundays are excluded.',
    examples: [{ title: 'Working days in a month', inputs: [{ label: 'From: 2026-10-01' }, { label: 'To: 2026-10-31' }], result: '22 working days' }],
    assumptions: 'This calculator excludes Saturdays and Sundays. Public holidays are not automatically excluded.',
    relatedTools: ['days-between-dates', 'date-difference-calculator', 'date-add-subtract', 'days-until-date'],
  },
  {
    id: 'countdown-timer',
    slug: 'countdown-timer',
    category: 'everyday',
    title: 'Countdown Timer',
    shortDescription: 'Set a countdown to any date and time and see time remaining in real time.',
    keywords: ['countdown', 'countdown timer', 'time until', 'event countdown'],
    aliases: ['countdown to date'],
    computation: 'countdown',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Remaining = Target datetime − Current datetime',
    explanation: 'This tool shows a live countdown to a target date and time, displaying days, hours, minutes, and seconds remaining.',
    examples: [{ title: 'New Year countdown', inputs: [{ label: 'Target: 2027-01-01 00:00' }], result: 'Live countdown display' }],
    relatedTools: ['days-until-date', 'days-between-dates', 'time-conversion'],
  },
  {
    id: 'time-conversion',
    slug: 'time-conversion',
    category: 'everyday',
    title: 'Time Conversion Calculator',
    shortDescription: 'Convert between seconds, minutes, hours, days, weeks, months, and years.',
    keywords: ['time conversion', 'convert time', 'seconds to hours', 'minutes to hours', 'time units'],
    aliases: ['time converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses the centralized time conversion registry with the base unit of seconds.',
    explanation: 'This converter uses the centralized conversion registry. All time units convert through seconds as the base unit.',
    examples: [{ title: 'Hours to seconds', inputs: [{ label: '2 hours' }], result: '7,200 seconds' }],
    relatedTools: ['speed-distance-time-calculator', 'length-conversion', 'weight-conversion'],
  },
  {
    id: 'timezone-converter',
    slug: 'timezone-converter',
    category: 'everyday',
    title: 'Timezone Converter',
    shortDescription: 'Convert a time from one timezone to another.',
    keywords: ['timezone converter', 'time zone converter', 'convert timezone', 'utc to local', 'ist to est'],
    aliases: ['time zone converter', 'world time converter'],
    computation: 'timezoneConvert',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses JavaScript Intl API with IANA timezone identifiers for accurate conversion.',
    explanation: 'This converter uses the browser\'s built-in Intl.DateTimeFormat API to convert times between IANA timezones. DST is handled automatically.',
    examples: [{ title: 'UTC to IST', inputs: [{ label: '12:00 UTC' }, { label: 'To: Asia/Kolkata' }], result: '17:30 IST' }],
    assumptions: 'Conversion uses the browser\'s Intl API. Daylight Saving Time is handled automatically based on the date.',
    relatedTools: ['time-conversion', 'unix-timestamp-converter', 'countdown-timer'],
  },
  {
    id: 'length-conversion',
    slug: 'length-conversion',
    category: 'everyday',
    title: 'Length Conversion',
    shortDescription: 'Convert between metric and imperial length units.',
    keywords: ['length conversion', 'meters to feet', 'km to miles', 'cm to inches', 'distance converter'],
    aliases: ['distance converter', 'length converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'All length units convert through meters as the base unit.',
    explanation: 'Convert between millimeters, centimeters, meters, kilometers, inches, feet, yards, miles, and nautical miles.',
    examples: [{ title: 'Meters to feet', inputs: [{ label: '1 m' }], result: '3.2808 ft' }],
    relatedTools: ['weight-conversion', 'area-conversion', 'volume-conversion', 'speed-conversion'],
  },
  {
    id: 'weight-conversion',
    slug: 'weight-conversion',
    category: 'everyday',
    title: 'Weight Conversion',
    shortDescription: 'Convert between metric and imperial weight units.',
    keywords: ['weight conversion', 'kg to lbs', 'grams to ounces', 'pounds to kg', 'mass converter'],
    aliases: ['mass converter', 'weight converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'All weight units convert through kilograms as the base unit.',
    explanation: 'Convert between milligrams, grams, kilograms, tonnes, ounces, pounds, and stone.',
    examples: [{ title: 'Kg to lbs', inputs: [{ label: '1 kg' }], result: '2.2046 lbs' }],
    relatedTools: ['length-conversion', 'volume-conversion', 'area-conversion', 'temperature-conversion'],
  },
  {
    id: 'temperature-conversion',
    slug: 'temperature-conversion',
    category: 'everyday',
    title: 'Temperature Conversion',
    shortDescription: 'Convert between Celsius, Fahrenheit, and Kelvin.',
    keywords: ['temperature conversion', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin converter', 'c to f'],
    aliases: ['celsius to fahrenheit', 'fahrenheit to celsius'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: '°F = (°C × 9/5) + 32; K = °C + 273.15',
    explanation: 'Temperature conversion uses special formulas rather than simple multiplication, because the scales have different zero points.',
    examples: [{ title: 'Celsius to Fahrenheit', inputs: [{ label: '25°C' }], result: '77°F' }],
    relatedTools: ['length-conversion', 'weight-conversion', 'speed-conversion', 'area-conversion'],
  },
  {
    id: 'area-conversion',
    slug: 'area-conversion',
    category: 'everyday',
    title: 'Area Conversion',
    shortDescription: 'Convert between square meters, square feet, acres, hectares, and more.',
    keywords: ['area conversion', 'square meters to square feet', 'acres to hectares', 'sq ft converter'],
    aliases: ['area converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'All area units convert through square meters as the base unit.',
    explanation: 'Convert between square millimeters, centimeters, meters, kilometers, hectares, acres, square feet, inches, yards, and miles.',
    examples: [{ title: 'Sq meters to sq feet', inputs: [{ label: '100 m²' }], result: '1,076.39 ft²' }],
    relatedTools: ['length-conversion', 'volume-conversion', 'weight-conversion'],
  },
  {
    id: 'volume-conversion',
    slug: 'volume-conversion',
    category: 'everyday',
    title: 'Volume Conversion',
    shortDescription: 'Convert between liters, gallons, cubic meters, cups, and more.',
    keywords: ['volume conversion', 'liters to gallons', 'ml to cups', 'cubic meters to liters', 'volume converter'],
    aliases: ['volume converter', 'capacity converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'All volume units convert through liters as the base unit.',
    explanation: 'Convert between milliliters, liters, cubic meters, cubic centimeters, cubic inches, cubic feet, US/UK gallons, quarts, pints, cups, and fluid ounces.',
    examples: [{ title: 'Liters to US gallons', inputs: [{ label: '10 L' }], result: '2.6417 gal' }],
    relatedTools: ['length-conversion', 'weight-conversion', 'area-conversion', 'temperature-conversion'],
  },
  {
    id: 'speed-conversion',
    slug: 'speed-conversion',
    category: 'everyday',
    title: 'Speed Conversion',
    shortDescription: 'Convert between m/s, km/h, mph, ft/s, and knots.',
    keywords: ['speed conversion', 'km/h to mph', 'm/s to km/h', 'knots to mph', 'speed converter'],
    aliases: ['speed converter', 'velocity converter'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'All speed units convert through meters/second as the base unit.',
    explanation: 'Convert between meters per second, kilometers per hour, miles per hour, feet per second, and knots.',
    examples: [{ title: 'km/h to mph', inputs: [{ label: '100 km/h' }], result: '62.14 mph' }],
    relatedTools: ['length-conversion', 'time-conversion', 'fuel-economy-conversion', 'speed-distance-time-calculator'],
  },
  {
    id: 'fuel-economy-conversion',
    slug: 'fuel-economy-conversion',
    category: 'everyday',
    title: 'Fuel Economy Conversion',
    shortDescription: 'Convert between km/L, mpg (US), mpg (UK), and L/100km.',
    keywords: ['fuel economy', 'km/l to mpg', 'mpg to l/100km', 'fuel conversion', 'mileage converter'],
    aliases: ['fuel converter', 'mileage conversion'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses inverse conversion for L/100km (100 ÷ km/L) and standard factors for mpg.',
    explanation: 'Fuel economy units have an inverse relationship (L/100km vs km/L), so this converter handles them specially rather than using simple multiplication.',
    examples: [{ title: 'km/L to mpg US', inputs: [{ label: '15 km/L' }], result: '35.26 mpg' }],
    relatedTools: ['speed-conversion', 'length-conversion', 'volume-conversion'],
  },
  {
    id: 'data-size-conversion',
    slug: 'data-size-conversion',
    category: 'everyday',
    title: 'Data Size Conversion',
    shortDescription: 'Convert between bits, bytes, KB, MB, GB, and TB.',
    keywords: ['data size conversion', 'mb to gb', 'kb to mb', 'bytes to mb', 'data converter', 'storage converter'],
    aliases: ['byte converter', 'storage conversion'],
    computation: 'unitConversion',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses binary units (1 KB = 1024 bytes) as the standard.',
    explanation: 'Convert between bits, bytes, kilobytes, megabytes, gigabytes, and terabytes using binary (base-1024) units.',
    examples: [{ title: 'MB to GB', inputs: [{ label: '2048 MB' }], result: '2 GB' }],
    relatedTools: ['length-conversion', 'weight-conversion', 'time-conversion'],
  },

  // ===== STUDENT =====
  {
    id: 'marks-percentage-calculator',
    slug: 'marks-percentage-calculator',
    category: 'student',
    title: 'Marks Percentage Calculator',
    shortDescription: 'Calculate the percentage from marks obtained and total marks.',
    keywords: ['marks percentage', 'percentage from marks', 'marks to percentage', 'exam percentage'],
    aliases: ['percentage from marks calculator'],
    computation: 'percentageFromMarks',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage = (Obtained Marks / Total Marks) × 100',
    explanation: 'This calculator converts your obtained marks and total marks into a percentage. Enter the marks you received and the maximum possible marks.',
    examples: [{ title: 'Exam percentage', inputs: [{ label: 'Obtained: 85' }, { label: 'Total: 100' }], result: '85%' }],
    relatedTools: ['marks-from-percentage', 'grade-calculator', 'cgpa-calculator', 'gpa-calculator', 'required-marks-calculator'],
  },
  {
    id: 'marks-from-percentage',
    slug: 'marks-from-percentage',
    category: 'student',
    title: 'Marks from Percentage Calculator',
    shortDescription: 'Find how many marks you need for a target percentage.',
    keywords: ['marks from percentage', 'percentage to marks', 'how many marks for percentage'],
    aliases: ['percentage to marks calculator'],
    computation: 'marksFromPercentage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Marks = (Percentage / 100) × Total Marks',
    explanation: 'This calculator tells you how many marks correspond to a given percentage of a total.',
    examples: [{ title: '75% of 200', inputs: [{ label: 'Percentage: 75%' }, { label: 'Total: 200' }], result: '150 marks' }],
    relatedTools: ['marks-percentage-calculator', 'required-marks-calculator', 'grade-calculator'],
  },
  {
    id: 'cgpa-calculator',
    slug: 'cgpa-calculator',
    category: 'student',
    title: 'CGPA Calculator',
    shortDescription: 'Calculate your CGPA from grade points and course credits.',
    keywords: ['cgpa calculator', 'cumulative grade point average', 'grade point average', 'cgpa'],
    aliases: ['cumulative grade point average calculator'],
    computation: 'cgpa',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'CGPA = Σ(Grade Point × Credits) / Σ(Credits)',
    explanation: 'CGPA (Cumulative Grade Point Average) is the weighted average of grade points across all courses, weighted by the credit hours of each course.',
    examples: [{ title: 'Two courses', inputs: [{ label: 'GP: 8, 9' }, { label: 'Credits: 3, 4' }], result: '(8×3 + 9×4) / (3+4) = 60/7 ≈ 8.57' }],
    relatedTools: ['cgpa-to-percentage', 'percentage-to-cgpa', 'gpa-calculator', 'sgpa-calculator', 'marks-percentage-calculator'],
    faq: [
      { question: 'What is CGPA?', answer: 'CGPA stands for Cumulative Grade Point Average. It is the weighted average of your grade points across all courses, where each course is weighted by its credit hours.' },
      { question: 'Is CGPA the same as GPA?', answer: 'CGPA typically refers to the cumulative average across all semesters, while GPA may refer to a single semester. The calculation method is the same.' },
    ],
  },
  {
    id: 'cgpa-to-percentage',
    slug: 'cgpa-to-percentage',
    category: 'student',
    title: 'CGPA to Percentage Calculator',
    shortDescription: 'Convert CGPA to percentage using the standard 9.5 multiplier.',
    keywords: ['cgpa to percentage', 'convert cgpa to percentage', 'cgpa percentage'],
    aliases: ['cgpa percentage calculator'],
    computation: 'cgpaToPercentage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Percentage = CGPA × 9.5 (standard formula used by many Indian universities)',
    explanation: 'The most common conversion from CGPA to percentage uses a multiplier of 9.5, as prescribed by many Indian universities. Some institutions use different multipliers — check with your institution.',
    examples: [{ title: '8.0 CGPA', inputs: [{ label: 'CGPA: 8.0' }], result: '8.0 × 9.5 = 76%' }],
    assumptions: 'The 9.5 multiplier is specific to certain Indian universities (e.g., CBSE). Your institution may use a different formula. Verify with your academic office.',
    relatedTools: ['cgpa-calculator', 'percentage-to-cgpa', 'gpa-calculator', 'marks-percentage-calculator'],
    faq: [
      { question: 'Why is 9.5 used as the multiplier?', answer: 'The 9.5 multiplier was derived by CBSE from historical data mapping CGPA to actual percentage marks. Other universities may use different values such as 10.' },
      { question: 'Does this formula work for all universities?', answer: 'No. The conversion formula varies by institution. Some use 10, some use 9.5, and some have their own formulas. Always verify with your university.' },
    ],
  },
  {
    id: 'percentage-to-cgpa',
    slug: 'percentage-to-cgpa',
    category: 'student',
    title: 'Percentage to CGPA Calculator',
    shortDescription: 'Convert a percentage to CGPA using the standard 9.5 divisor.',
    keywords: ['percentage to cgpa', 'convert percentage to cgpa', 'percentage cgpa'],
    aliases: ['percentage to cgpa converter'],
    computation: 'percentageToCGPA',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'CGPA = Percentage / 9.5',
    explanation: 'This is the reverse of the CGPA-to-percentage conversion. Divide your percentage by 9.5 to get CGPA. Verify the multiplier with your institution.',
    examples: [{ title: '76% to CGPA', inputs: [{ label: 'Percentage: 76%' }], result: '76 / 9.5 ≈ 8.0 CGPA' }],
    assumptions: 'Uses the 9.5 divisor. Some institutions use 10 or another value.',
    relatedTools: ['cgpa-to-percentage', 'cgpa-calculator', 'gpa-calculator', 'marks-percentage-calculator'],
  },
  {
    id: 'gpa-calculator',
    slug: 'gpa-calculator',
    category: 'student',
    title: 'GPA Calculator',
    shortDescription: 'Calculate your GPA on a 4.0 scale from course grades and credits.',
    keywords: ['gpa calculator', 'grade point average', '4.0 scale gpa', 'semester gpa'],
    aliases: ['grade point average calculator'],
    computation: 'gpa',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'GPA = Σ(Grade Point × Credits) / Σ(Credits)',
    explanation: 'GPA is the weighted average of grade points on a 4.0 scale. Each course is weighted by its credit hours.',
    examples: [{ title: 'Three courses', inputs: [{ label: 'GP: 3.5, 4.0, 3.0' }, { label: 'Credits: 3, 4, 3' }], result: '(3.5×3 + 4×4 + 3×3) / (3+4+3) = 32/10 = 3.2' }],
    relatedTools: ['cgpa-calculator', 'sgpa-calculator', 'cgpa-to-percentage', 'marks-percentage-calculator'],
  },
  {
    id: 'sgpa-calculator',
    slug: 'sgpa-calculator',
    category: 'student',
    title: 'SGPA Calculator',
    shortDescription: 'Calculate your Semester Grade Point Average (SGPA).',
    keywords: ['sgpa calculator', 'semester grade point average', 'sgpa', 'semester gpa'],
    aliases: ['semester gpa calculator'],
    computation: 'sgpa',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'SGPA = Σ(Grade Point × Credits) / Σ(Credits) for one semester',
    explanation: 'SGPA is the weighted average of grade points for a single semester. It is calculated the same way as GPA but covers only one semester\'s courses.',
    examples: [{ title: 'Semester SGPA', inputs: [{ label: 'GP: 8, 7, 9' }, { label: 'Credits: 3, 4, 3' }], result: '(8×3 + 7×4 + 9×3) / (3+4+3) = 79/10 = 7.9' }],
    relatedTools: ['cgpa-calculator', 'gpa-calculator', 'cgpa-to-percentage', 'grade-calculator'],
  },
  {
    id: 'attendance-calculator',
    slug: 'attendance-calculator',
    category: 'student',
    title: 'Attendance Percentage Calculator',
    shortDescription: 'Calculate your attendance percentage from classes attended and total classes.',
    keywords: ['attendance calculator', 'attendance percentage', 'attendance percentage calculator', 'class attendance'],
    aliases: ['attendance percentage calculator'],
    computation: 'attendancePercentage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Attendance % = (Classes Attended / Total Classes) × 100',
    explanation: 'This calculator shows your attendance percentage and tells you how many more classes you need to attend (or can skip) to reach a target.',
    examples: [{ title: 'Current attendance', inputs: [{ label: 'Attended: 45' }, { label: 'Total: 60' }], result: '75%' }],
    relatedTools: ['required-attendance-calculator', 'marks-percentage-calculator', 'percentage-calculator'],
  },
  {
    id: 'required-attendance-calculator',
    slug: 'required-attendance-calculator',
    category: 'student',
    title: 'Required Attendance Calculator',
    shortDescription: 'Find how many classes you must attend to reach your attendance target.',
    keywords: ['required attendance', 'attendance target', 'how many classes to attend', 'attendance requirement'],
    aliases: ['attendance target calculator'],
    computation: 'requiredAttendance',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Classes to attend = ceil((Target% × Total − 100 × Attended) / (100 − Target%))',
    explanation: 'This calculator determines how many consecutive classes you must attend to reach your target attendance percentage, or how many you can skip while maintaining it.',
    examples: [{ title: 'Reach 75%', inputs: [{ label: 'Attended: 45' }, { label: 'Total: 60' }, { label: 'Target: 75%' }], result: 'Already above target. Can skip 0 classes.' }],
    relatedTools: ['attendance-calculator', 'marks-percentage-calculator', 'percentage-calculator'],
  },
  {
    id: 'grade-calculator',
    slug: 'grade-calculator',
    category: 'student',
    title: 'Grade Calculator',
    shortDescription: 'Calculate your final grade from percentage or marks using a standard grading scale.',
    keywords: ['grade calculator', 'final grade', 'letter grade', 'grade from percentage'],
    aliases: ['final grade calculator'],
    computation: 'gradeFromPercentage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Uses standard 10-point grading scale: A+ (90+), A (80-89), B+ (70-79), B (60-69), C (50-59), D (40-49), F (<40)',
    explanation: 'This calculator converts your percentage into a letter grade and grade point using a standard 10-point scale. Different institutions may use different scales.',
    examples: [{ title: '85% grade', inputs: [{ label: 'Percentage: 85%' }], result: 'Grade A, Grade Point 9' }],
    assumptions: 'This uses a common 10-point grading scale. Your institution may use a different scale.',
    relatedTools: ['marks-percentage-calculator', 'cgpa-calculator', 'gpa-calculator', 'sgpa-calculator'],
  },
  {
    id: 'required-marks-calculator',
    slug: 'required-marks-calculator',
    category: 'student',
    title: 'Required Marks Calculator',
    shortDescription: 'Calculate how many marks you need in remaining exams to reach a target percentage.',
    keywords: ['required marks', 'target marks', 'how many marks needed', 'exam target calculator'],
    aliases: ['target marks calculator'],
    computation: 'requiredMarks',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Required Marks = (Target% × Total Marks) − Current Obtained',
    explanation: 'This calculator helps you plan: given your current marks, how many more marks you need from upcoming exams to reach your target overall percentage.',
    examples: [{ title: 'Target 80%', inputs: [{ label: 'Current: 350/500' }, { label: 'Remaining: 300' }, { label: 'Target: 80%' }], result: 'Need 490 − 350 = 140 out of 300 (46.67%)' }],
    relatedTools: ['marks-percentage-calculator', 'grade-calculator', 'attendance-calculator'],
  },
  {
    id: 'exam-score-calculator',
    slug: 'exam-score-calculator',
    category: 'student',
    title: 'Exam Score Calculator',
    shortDescription: 'Calculate your total exam score from multiple sections with different weights.',
    keywords: ['exam score', 'test score', 'weighted exam score', 'final exam calculator'],
    aliases: ['final exam score calculator'],
    computation: 'weightedAverage',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Total Score = Σ(Section Score × Section Weight) / Σ(Weights)',
    explanation: 'This calculator computes a weighted total from multiple exam sections. Each section can have a different maximum score and weight.',
    examples: [{ title: 'Three sections', inputs: [{ label: 'Scores: 80, 90, 70' }, { label: 'Weights: 2, 3, 1' }], result: '(80×2 + 90×3 + 70×1) / 6 = 500/6 ≈ 83.33' }],
    relatedTools: ['grade-calculator', 'weighted-average-calculator', 'marks-percentage-calculator'],
  },

  // ===== CAREER =====
  {
    id: 'salary-increment-calculator',
    slug: 'salary-increment-calculator',
    category: 'career',
    title: 'Salary Increment Calculator',
    shortDescription: 'Calculate your new salary after a percentage increment.',
    keywords: ['salary increment', 'salary increase', 'pay raise calculator', 'salary hike calculator'],
    aliases: ['salary increase calculator', 'pay raise calculator'],
    computation: 'salaryIncrement',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'New Salary = Current Salary + (Current Salary × Increment% / 100)',
    explanation: 'This calculator shows your new salary after a percentage-based increment, plus the actual increment amount.',
    examples: [{ title: '10% increment', inputs: [{ label: 'Current: $50,000' }, { label: 'Increment: 10%' }], result: 'New Salary = $55,000, Increment = $5,000' }],
    relatedTools: ['salary-hike-percentage-calculator', 'salary-comparison-calculator', 'ctc-calculator'],
  },
  {
    id: 'salary-hike-percentage-calculator',
    slug: 'salary-hike-percentage-calculator',
    category: 'career',
    title: 'Salary Hike Percentage Calculator',
    shortDescription: 'Calculate the percentage hike between your old and new salary.',
    keywords: ['salary hike percentage', 'hike percentage', 'salary hike', 'percentage hike'],
    aliases: ['hike percentage calculator'],
    computation: 'salaryHikePercentage',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Hike % = ((New Salary − Old Salary) / Old Salary) × 100',
    explanation: 'This calculator finds the percentage increase between your previous and new salary.',
    examples: [{ title: 'Salary hike', inputs: [{ label: 'Old: $50,000' }, { label: 'New: $60,000' }], result: 'Hike = 20%' }],
    relatedTools: ['salary-increment-calculator', 'salary-comparison-calculator', 'percentage-change-calculator'],
  },
  {
    id: 'salary-comparison-calculator',
    slug: 'salary-comparison-calculator',
    category: 'career',
    title: 'Salary Comparison Calculator',
    shortDescription: 'Compare two salary offers and see the difference in amount and percentage.',
    keywords: ['salary comparison', 'compare salary', 'salary difference', 'job offer comparison'],
    aliases: ['compare salary calculator'],
    computation: 'salaryComparison',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Difference = |A − B|; Percentage Difference = (Difference / Average) × 100',
    explanation: 'This calculator compares two salary offers, showing the absolute difference and the percentage difference relative to their average.',
    examples: [{ title: 'Two offers', inputs: [{ label: 'A: $60,000' }, { label: 'B: $75,000' }], result: 'Difference = $15,000, % Difference = 22.22%' }],
    relatedTools: ['salary-increment-calculator', 'salary-hike-percentage-calculator', 'ctc-calculator'],
  },
  {
    id: 'experience-calculator',
    slug: 'experience-calculator',
    category: 'career',
    title: 'Experience Calculator',
    shortDescription: 'Calculate your total work experience in years and months.',
    keywords: ['experience calculator', 'work experience', 'total experience', 'years of experience'],
    aliases: ['work experience calculator'],
    computation: 'experience',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Counts full years and months between start and end dates.',
    explanation: 'This calculator measures your total work experience from your joining date to the end date (or today), showing years, months, and total days.',
    examples: [{ title: 'Work experience', inputs: [{ label: 'Start: 2020-06-01' }, { label: 'End: 2026-10-07' }], result: '6 years, 4 months' }],
    relatedTools: ['age-calculator', 'date-difference-calculator', 'notice-period-calculator'],
  },
  {
    id: 'notice-period-calculator',
    slug: 'notice-period-calculator',
    category: 'career',
    title: 'Notice Period Calculator',
    shortDescription: 'Calculate your last working day from your notice start date and notice period.',
    keywords: ['notice period', 'last working day', 'notice period calculator', 'resignation date'],
    aliases: ['last working day calculator'],
    computation: 'noticePeriod',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Last Working Day = Notice Start Date + Notice Period (in days)',
    explanation: 'This calculator finds your last working day by adding the notice period (in days) to your resignation or notice start date.',
    examples: [{ title: '60-day notice', inputs: [{ label: 'Start: 2026-10-01' }, { label: 'Days: 60' }], result: 'Last working day: 2026-11-30' }],
    relatedTools: ['experience-calculator', 'date-add-subtract', 'working-days-calculator'],
  },
  {
    id: 'ctc-calculator',
    slug: 'ctc-calculator',
    category: 'career',
    title: 'CTC to Take-Home Calculator',
    shortDescription: 'Estimate your monthly take-home pay from your annual CTC and deductions.',
    keywords: ['ctc calculator', 'ctc to take home', 'in hand salary', 'ctc breakdown', 'salary calculator'],
    aliases: ['in hand salary calculator', 'take home salary calculator'],
    computation: 'ctcToTakeHome',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Monthly Take-Home = (CTC − Annual Deductions) / 12',
    explanation: 'CTC (Cost to Company) includes all benefits and deductions. This calculator estimates your monthly take-home by subtracting annual deductions (tax, PF, insurance, etc.) from your CTC and dividing by 12.',
    examples: [{ title: 'CTC estimation', inputs: [{ label: 'CTC: $60,000' }, { label: 'Deductions: $10,000' }], result: 'Monthly Take-Home ≈ $4,167' }],
    assumptions: 'This is a simplified estimate. Actual take-home depends on your tax regime, country, state, deductions, benefits, and employer policies. Not financial or tax advice.',
    relatedTools: ['salary-increment-calculator', 'salary-comparison-calculator', 'salary-hike-percentage-calculator'],
    faq: [
      { question: 'How accurate is this estimate?', answer: 'This is a rough estimate that only subtracts a single deductions figure from CTC. Your actual take-home depends on income tax, social security, health insurance, retirement contributions, and other factors specific to your country and employer.' },
      { question: 'What is CTC?', answer: 'CTC stands for Cost to Company — the total amount an employer spends on you annually, including salary, bonuses, benefits, and employer-side contributions. It is typically higher than your take-home pay.' },
    ],
  },
  {
    id: 'leave-calculator',
    slug: 'leave-calculator',
    category: 'career',
    title: 'Leave Balance Calculator',
    shortDescription: 'Track your leave balance from total, taken, and planned leave days.',
    keywords: ['leave calculator', 'leave balance', 'leave days', 'vacation days calculator'],
    aliases: ['leave balance calculator'],
    computation: 'leaveBalance',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Remaining = Total Leave − Taken Leave − Planned Leave',
    explanation: 'This calculator shows how many leave days you have remaining after accounting for taken and planned leave.',
    examples: [{ title: 'Leave balance', inputs: [{ label: 'Total: 30' }, { label: 'Taken: 12' }, { label: 'Planned: 5' }], result: 'Remaining: 13 days' }],
    relatedTools: ['working-days-calculator', 'date-add-subtract', 'notice-period-calculator'],
  },

  // ===== MONEY =====
  {
    id: 'emi-calculator',
    slug: 'emi-calculator',
    category: 'money',
    title: 'EMI Calculator',
    shortDescription: 'Calculate your monthly EMI, total payment, and total interest for any loan.',
    keywords: ['emi calculator', 'loan emi', 'monthly installment', 'home loan emi', 'car loan emi'],
    aliases: ['loan emi calculator', 'monthly installment calculator'],
    computation: 'emi',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'EMI = P × r × (1+r)^n / ((1+r)^n − 1), where r = monthly rate, n = months',
    explanation: 'EMI (Equated Monthly Installment) is the fixed monthly payment you make on a loan. It covers both principal and interest. The formula uses the monthly interest rate and the number of months.',
    examples: [{ title: 'Home loan EMI', inputs: [{ label: 'Principal: $200,000' }, { label: 'Rate: 7.5%' }, { label: 'Tenure: 20 years' }], result: 'EMI ≈ $1,611.19/month' }],
    assumptions: 'Assumes fixed-rate loan with equal monthly payments. Does not account for prepayments, floating rates, or fees.',
    relatedTools: ['loan-interest-calculator', 'simple-interest-calculator', 'compound-interest-calculator', 'sip-calculator'],
    faq: [
      { question: 'What is EMI?', answer: 'EMI stands for Equated Monthly Installment. It is the fixed amount you pay each month towards a loan, covering both principal repayment and interest.' },
      { question: 'How is the interest rate used?', answer: 'The annual interest rate is divided by 12 to get the monthly rate. For 7.5% annual, the monthly rate is 0.625%.' },
    ],
  },
  {
    id: 'loan-interest-calculator',
    slug: 'loan-interest-calculator',
    category: 'money',
    title: 'Loan Interest Calculator',
    shortDescription: 'Calculate total interest payable on a loan over its tenure.',
    keywords: ['loan interest', 'interest on loan', 'total interest calculator', 'loan cost'],
    aliases: ['loan interest calculator'],
    computation: 'loanInterest',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Total Interest = (EMI × Months) − Principal',
    explanation: 'This calculator shows the total interest you will pay over the life of a loan, based on the principal, rate, and tenure.',
    examples: [{ title: 'Loan cost', inputs: [{ label: 'Principal: $100,000' }, { label: 'Rate: 8%' }, { label: 'Tenure: 15 years' }], result: 'Total Interest ≈ $72,018' }],
    relatedTools: ['emi-calculator', 'compound-interest-calculator', 'simple-interest-calculator'],
  },
  {
    id: 'sip-calculator',
    slug: 'sip-calculator',
    category: 'money',
    title: 'SIP Calculator',
    shortDescription: 'Calculate the future value of your monthly SIP investments.',
    keywords: ['sip calculator', 'systematic investment plan', 'mutual fund sip', 'monthly investment calculator'],
    aliases: ['systematic investment plan calculator'],
    computation: 'sip',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'FV = P × ((1+r)^n − 1) / r × (1+r), where r = monthly rate, n = months',
    explanation: 'A SIP (Systematic Investment Plan) invests a fixed amount monthly. The future value is calculated using the future value of an annuity formula with the expected monthly return rate.',
    examples: [{ title: 'Monthly SIP', inputs: [{ label: 'Monthly: $500' }, { label: 'Rate: 12%' }, { label: 'Years: 10' }], result: 'Invested: $60,000, Future Value ≈ $115,019' }],
    assumptions: 'Assumes constant monthly investment and fixed annual return rate. Actual returns vary. This is an estimate, not financial advice.',
    relatedTools: ['compound-interest-calculator', 'fd-calculator', 'rd-calculator', 'emi-calculator'],
  },
  {
    id: 'fd-calculator',
    slug: 'fd-calculator',
    category: 'money',
    title: 'FD Calculator',
    shortDescription: 'Calculate the maturity amount and interest on a Fixed Deposit.',
    keywords: ['fd calculator', 'fixed deposit', 'fd maturity', 'term deposit calculator'],
    aliases: ['fixed deposit calculator'],
    computation: 'fd',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Maturity = P × (1 + r/n)^(n×t)',
    explanation: 'A Fixed Deposit (FD) compounds interest at a fixed rate. The maturity amount depends on the principal, interest rate, tenure, and compounding frequency.',
    examples: [{ title: 'FD maturity', inputs: [{ label: 'Principal: $10,000' }, { label: 'Rate: 6.5%' }, { label: 'Years: 5' }, { label: 'Frequency: Quarterly' }], result: 'Maturity ≈ $13,814' }],
    assumptions: 'Assumes fixed interest rate for the entire tenure. Actual rates may vary. Not financial advice.',
    relatedTools: ['rd-calculator', 'sip-calculator', 'compound-interest-calculator', 'simple-interest-calculator'],
  },
  {
    id: 'rd-calculator',
    slug: 'rd-calculator',
    category: 'money',
    title: 'RD Calculator',
    shortDescription: 'Calculate the maturity amount on a Recurring Deposit.',
    keywords: ['rd calculator', 'recurring deposit', 'rd maturity', 'monthly deposit calculator'],
    aliases: ['recurring deposit calculator'],
    computation: 'rd',
    needsClient: true,
    commercialIntent: 'high',
    formula: 'Uses quarterly compounding on monthly deposits with the standard RD formula.',
    explanation: 'A Recurring Deposit (RD) requires fixed monthly deposits and compounds interest quarterly. The maturity amount is the sum of all deposits plus accumulated interest.',
    examples: [{ title: 'RD maturity', inputs: [{ label: 'Monthly: $1,000' }, { label: 'Rate: 6%' }, { label: 'Months: 60' }], result: 'Invested: $60,000, Maturity ≈ $69,771' }],
    assumptions: 'Uses quarterly compounding. Actual terms may vary by bank. Not financial advice.',
    relatedTools: ['fd-calculator', 'sip-calculator', 'compound-interest-calculator'],
  },
  {
    id: 'gst-calculator',
    slug: 'gst-calculator',
    category: 'money',
    title: 'GST Calculator',
    shortDescription: 'Calculate GST inclusive and exclusive amounts for any GST rate.',
    keywords: ['gst calculator', 'gst inclusive', 'gst exclusive', 'tax calculator', 'gst amount'],
    aliases: ['gst inclusive exclusive calculator'],
    computation: 'gst',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Exclusive: GST = Amount × Rate/100; Inclusive: Base = Amount / (1 + Rate/100)',
    explanation: 'This calculator handles both GST-inclusive (GST is already in the price) and GST-exclusive (GST is added to the price) calculations.',
    examples: [{ title: 'GST exclusive', inputs: [{ label: 'Amount: $1,000' }, { label: 'GST: 18%' }, { label: 'Mode: Exclusive' }], result: 'GST = $180, Total = $1,180' }],
    assumptions: 'GST rates vary by country and product category. Verify the applicable rate for your jurisdiction.',
    relatedTools: ['discount-calculator', 'percentage-calculator', 'simple-interest-calculator'],
  },
  {
    id: 'inflation-calculator',
    slug: 'inflation-calculator',
    category: 'money',
    title: 'Inflation Calculator',
    shortDescription: 'Calculate how much today\'s money will be worth in the future due to inflation.',
    keywords: ['inflation calculator', 'future value of money', 'purchasing power', 'inflation impact'],
    aliases: ['future value calculator', 'purchasing power calculator'],
    computation: 'inflation',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Future Value = Present Value × (1 + Rate)^Years',
    explanation: 'This calculator shows how inflation erodes purchasing power over time. It calculates the future cost of goods or the future value of money at a given inflation rate.',
    examples: [{ title: 'Future cost', inputs: [{ label: 'Today: $100' }, { label: 'Rate: 5%' }, { label: 'Years: 10' }], result: 'Future Value ≈ $162.89' }],
    assumptions: 'Assumes constant inflation rate. Actual rates fluctuate. Not financial advice.',
    relatedTools: ['compound-interest-calculator', 'sip-calculator', 'percentage-change-calculator'],
  },

  // ===== DEVELOPER =====
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    category: 'developer',
    title: 'JSON Formatter',
    shortDescription: 'Format and pretty-print JSON with customizable indentation.',
    keywords: ['json formatter', 'pretty print json', 'format json', 'beautify json', 'json beautifier'],
    aliases: ['json beautifier', 'pretty json'],
    computation: 'formatJSON',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Parses JSON and re-serializes with indentation.',
    explanation: 'This tool parses your JSON and re-serializes it with proper indentation for readability. All processing happens locally in your browser — your data never leaves your device.',
    examples: [{ title: 'Format JSON', inputs: [{ label: '{"name":"John","age":30}' }], result: '{\n  "name": "John",\n  "age": 30\n}' }],
    relatedTools: ['json-validator', 'json-minifier', 'base64-encoder', 'url-encoder'],
    faq: [
      { question: 'Is my JSON data sent to a server?', answer: 'No. All formatting happens entirely in your browser. Your JSON data is never transmitted to any server.' },
    ],
  },
  {
    id: 'json-validator',
    slug: 'json-validator',
    category: 'developer',
    title: 'JSON Validator',
    shortDescription: 'Validate JSON and find syntax errors with line and column numbers.',
    keywords: ['json validator', 'validate json', 'json checker', 'json syntax error'],
    aliases: ['json checker'],
    computation: 'validateJSON',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Attempts to parse JSON and reports the exact error location.',
    explanation: 'This tool validates your JSON syntax and reports errors with line and column numbers to help you fix issues quickly.',
    examples: [{ title: 'Invalid JSON', inputs: [{ label: '{"name": John}' }], result: 'Error at line 1, column 10: Unexpected token J' }],
    relatedTools: ['json-formatter', 'json-minifier', 'base64-encoder'],
  },
  {
    id: 'json-minifier',
    slug: 'json-minifier',
    category: 'developer',
    title: 'JSON Minifier',
    shortDescription: 'Minify JSON by removing whitespace and reducing file size.',
    keywords: ['json minifier', 'minify json', 'compress json', 'json compactor'],
    aliases: ['json compressor'],
    computation: 'minifyJSON',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Parses JSON and re-serializes without whitespace.',
    explanation: 'This tool removes all unnecessary whitespace from JSON to reduce its size. Useful for production deployments and API responses.',
    examples: [{ title: 'Minify', inputs: [{ label: '{\n  "name": "John"\n}' }], result: '{"name":"John"}' }],
    relatedTools: ['json-formatter', 'json-validator', 'base64-encoder'],
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    category: 'developer',
    title: 'Base64 Encoder',
    shortDescription: 'Encode text or strings to Base64 format.',
    keywords: ['base64 encoder', 'encode base64', 'base64 encode', 'btoa'],
    aliases: ['base64 encode'],
    computation: 'base64Encode',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Converts text to UTF-8 bytes, then to Base64.',
    explanation: 'Base64 encoding converts binary or text data into a safe ASCII string. This tool handles Unicode characters correctly using UTF-8 encoding.',
    examples: [{ title: 'Encode text', inputs: [{ label: 'Hello, World!' }], result: 'SGVsbG8sIFdvcmxkIQ==' }],
    relatedTools: ['base64-decoder', 'url-encoder', 'json-formatter'],
  },
  {
    id: 'base64-decoder',
    slug: 'base64-decoder',
    category: 'developer',
    title: 'Base64 Decoder',
    shortDescription: 'Decode Base64 strings back to readable text.',
    keywords: ['base64 decoder', 'decode base64', 'base64 decode', 'atob'],
    aliases: ['base64 decode'],
    computation: 'base64Decode',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Decodes Base64 to bytes, then interprets as UTF-8.',
    explanation: 'This tool decodes a Base64 string back to its original text. It handles UTF-8 characters correctly.',
    examples: [{ title: 'Decode Base64', inputs: [{ label: 'SGVsbG8sIFdvcmxkIQ==' }], result: 'Hello, World!' }],
    relatedTools: ['base64-encoder', 'url-decoder', 'jwt-decoder'],
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    category: 'developer',
    title: 'URL Encoder',
    shortDescription: 'Encode text for safe use in URLs.',
    keywords: ['url encoder', 'encode url', 'percent encoding', 'uri encode', 'urlencode'],
    aliases: ['percent encoding', 'uri encoder'],
    computation: 'urlEncode',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Uses encodeURIComponent to encode special characters.',
    explanation: 'URL encoding converts special characters to percent-encoded form so they can be safely included in a URL.',
    examples: [{ title: 'Encode URL', inputs: [{ label: 'hello world & foo' }], result: 'hello%20world%20%26%20foo' }],
    relatedTools: ['url-decoder', 'base64-encoder', 'json-formatter'],
  },
  {
    id: 'url-decoder',
    slug: 'url-decoder',
    category: 'developer',
    title: 'URL Decoder',
    shortDescription: 'Decode percent-encoded URL strings back to readable text.',
    keywords: ['url decoder', 'decode url', 'percent decode', 'uri decode', 'urldecode'],
    aliases: ['percent decoding', 'uri decoder'],
    computation: 'urlDecode',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Uses decodeURIComponent to decode percent-encoded characters.',
    explanation: 'This tool reverses URL encoding, converting percent-encoded characters back to their original form.',
    examples: [{ title: 'Decode URL', inputs: [{ label: 'hello%20world%20%26%20foo' }], result: 'hello world & foo' }],
    relatedTools: ['url-encoder', 'base64-decoder', 'json-validator'],
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    category: 'developer',
    title: 'UUID Generator',
    shortDescription: 'Generate one or more UUID v4 identifiers.',
    keywords: ['uuid generator', 'guid generator', 'uuid v4', 'unique identifier', 'uuid'],
    aliases: ['guid generator'],
    computation: 'generateUUIDs',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Generates RFC 4122 v4 UUIDs using crypto.randomUUID or a fallback.',
    explanation: 'UUID (Universally Unique Identifier) version 4 uses random numbers to create identifiers. This tool uses the browser\'s crypto API when available.',
    examples: [{ title: 'Generate UUID', inputs: [{ label: 'Count: 1' }], result: 'a1b2c3d4-e5f6-4789-abcd-ef0123456789' }],
    relatedTools: ['jwt-decoder', 'base64-encoder', 'unix-timestamp-converter'],
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    category: 'developer',
    title: 'JWT Decoder',
    shortDescription: 'Decode JWT tokens to inspect the header and payload (no signature verification).',
    keywords: ['jwt decoder', 'decode jwt', 'json web token', 'jwt payload', 'token decoder'],
    aliases: ['json web token decoder'],
    computation: 'decodeJWT',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Base64url-decodes the header and payload segments of the JWT.',
    explanation: 'This tool decodes the header and payload of a JWT (JSON Web Token) for inspection. It does NOT verify the signature — decoding only reads the content, it does not prove authenticity.',
    examples: [{ title: 'Decode JWT', inputs: [{ label: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.signature' }], result: 'Header: {"alg":"HS256"}, Payload: {"sub":"1234567890"}' }],
    assumptions: 'This tool only decodes JWTs. It does not verify signatures. Never trust decoded JWT content for authorization decisions without proper server-side verification.',
    relatedTools: ['base64-decoder', 'uuid-generator', 'json-formatter'],
    faq: [
      { question: 'Is decoding a JWT safe?', answer: 'Decoding only reads the content. It does not verify that the token is authentic or has not been tampered with. Anyone can decode a JWT — that is by design. Security comes from the signature, which must be verified server-side with the secret key.' },
    ],
  },
  {
    id: 'unix-timestamp-converter',
    slug: 'unix-timestamp-converter',
    category: 'developer',
    title: 'Unix Timestamp Converter',
    shortDescription: 'Convert between Unix timestamps and human-readable dates.',
    keywords: ['unix timestamp', 'epoch converter', 'timestamp converter', 'unix to date', 'date to unix'],
    aliases: ['epoch converter', 'timestamp converter'],
    computation: 'unixTimestamp',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Converts seconds/milliseconds since Jan 1, 1970 to a date and vice versa.',
    explanation: 'This converter handles both directions: timestamp to date and date to timestamp. It auto-detects whether the timestamp is in seconds or milliseconds.',
    examples: [{ title: 'Timestamp to date', inputs: [{ label: '1696032000' }], result: '2023-09-30 00:00:00 UTC' }],
    relatedTools: ['timezone-converter', 'date-add-subtract', 'uuid-generator'],
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    category: 'developer',
    title: 'Regex Tester',
    shortDescription: 'Test regular expressions against input text and see all matches.',
    keywords: ['regex tester', 'regex tester', 'regular expression', 'pattern matching', 'regex online'],
    aliases: ['regular expression tester', 'regex matcher'],
    computation: 'testRegex',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Compiles the regex with flags and executes against the test string.',
    explanation: 'This tool lets you test regular expressions against any text. Enter a pattern, flags, and test string to see all matches with their positions and capture groups.',
    examples: [{ title: 'Find emails', inputs: [{ label: 'Pattern: \\w+@\\w+\\.\\w+' }, { label: 'Test: user@example.com' }], result: 'Match: user@example.com at index 0' }],
    relatedTools: ['json-formatter', 'url-encoder', 'base64-encoder'],
  },
  {
    id: 'html-formatter',
    slug: 'html-formatter',
    category: 'developer',
    title: 'HTML Formatter',
    shortDescription: 'Format and indent HTML for readability.',
    keywords: ['html formatter', 'format html', 'beautify html', 'html beautifier', 'indent html'],
    aliases: ['html beautifier'],
    computation: 'formatHTML',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Parses HTML tags and applies indentation based on nesting.',
    explanation: 'This tool reformats HTML by adding proper indentation based on tag nesting. It handles void elements (br, img, input) correctly.',
    examples: [{ title: 'Format HTML', inputs: [{ label: '<div><p>Hello</p></div>' }], result: '<div>\n  <p>Hello</p>\n</div>' }],
    relatedTools: ['css-formatter', 'json-formatter', 'url-encoder'],
  },
  {
    id: 'css-formatter',
    slug: 'css-formatter',
    category: 'developer',
    title: 'CSS Formatter',
    shortDescription: 'Format and indent CSS for readability.',
    keywords: ['css formatter', 'format css', 'beautify css', 'css beautifier', 'indent css'],
    aliases: ['css beautifier'],
    computation: 'formatCSS',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Parses CSS rules and applies indentation.',
    explanation: 'This tool reformats CSS by adding proper indentation for properties within rules.',
    examples: [{ title: 'Format CSS', inputs: [{ label: 'body{color:red;font-size:14px;}' }], result: 'body {\n  color: red;\n  font-size: 14px;\n}' }],
    relatedTools: ['html-formatter', 'json-formatter', 'base64-encoder'],
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    category: 'developer',
    title: 'Color Converter',
    shortDescription: 'Convert between HEX, RGB, and HSL color formats.',
    keywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hsl converter', 'color format'],
    aliases: ['hex to rgb converter', 'rgb to hex converter'],
    computation: 'colorConvert',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'HEX ↔ RGB: direct channel mapping. RGB ↔ HSL: standard color space conversion.',
    explanation: 'This tool converts colors between HEX, RGB, and HSL formats. Enter a color in any format and see it in all others.',
    examples: [{ title: 'HEX to RGB', inputs: [{ label: '#FF6B35' }], result: 'RGB: 255, 107, 53 | HSL: 16°, 100%, 60%' }],
    relatedTools: ['html-formatter', 'css-formatter', 'json-formatter'],
  },
  {
    id: 'text-statistics',
    slug: 'text-statistics',
    category: 'developer',
    title: 'Text Statistics',
    shortDescription: 'Count characters, words, sentences, paragraphs, and lines in text.',
    keywords: ['text statistics', 'word count', 'character count', 'text counter', 'letter count'],
    aliases: ['word counter', 'character counter'],
    computation: 'textStats',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Counts characters, words (whitespace-separated), sentences (punctuation-based), paragraphs (double-newline), and lines.',
    explanation: 'This tool provides a comprehensive text analysis: character count (with and without spaces), word count, sentence count, paragraph count, and line count.',
    examples: [{ title: 'Count text', inputs: [{ label: 'Hello world. This is a test.' }], result: 'Characters: 27, Words: 5, Sentences: 2' }],
    relatedTools: ['case-converter', 'json-formatter', 'url-encoder'],
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    category: 'developer',
    title: 'Case Converter',
    shortDescription: 'Convert text between uppercase, lowercase, title, camel, snake, and kebab case.',
    keywords: ['case converter', 'uppercase', 'lowercase', 'camelcase', 'snake_case', 'kebab-case', 'title case'],
    aliases: ['text case converter'],
    computation: 'caseTransform',
    needsClient: true,
    commercialIntent: 'medium',
    formula: 'Applies standard string transformations for each case style.',
    explanation: 'This tool converts text between various casing conventions: UPPER, lower, Title, Sentence, camelCase, PascalCase, snake_case, and kebab-case.',
    examples: [{ title: 'To snake_case', inputs: [{ label: 'Hello World' }], result: 'hello_world' }],
    relatedTools: ['text-statistics', 'json-formatter', 'url-encoder'],
  },

  // ===== EXAMS =====
  {
    id: 'ssc-cgl-score-calculator',
    slug: 'ssc-cgl-score-calculator',
    category: 'exams',
    title: 'SSC CGL Score Calculator',
    shortDescription: 'Calculate your SSC CGL Tier 1 score with negative marking.',
    keywords: ['ssc cgl score', 'ssc cgl marks', 'ssc cgl calculator', 'ssc cgl negative marking'],
    aliases: ['ssc cgl tier 1 score calculator'],
    computation: 'sscCglScore',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Score = (Correct × 2) − (Incorrect × 0.5)',
    explanation: 'This calculator computes your estimated SSC CGL Tier 1 score. Each correct answer awards 2 marks, and each wrong answer deducts 0.5 marks (negative marking).',
    examples: [{ title: 'Score estimate', inputs: [{ label: 'Correct: 80' }, { label: 'Incorrect: 10' }, { label: 'Skipped: 10' }], result: 'Score = (80×2) − (10×0.5) = 160 − 5 = 155' }],
    assumptions: 'Based on SSC CGL Tier 1 exam pattern. Each question is 2 marks with 0.5 negative marking per wrong answer. Verify the marking scheme for your specific exam session.',
    source: {
      name: 'Staff Selection Commission',
      url: 'https://ssc.nic.in',
      effectiveDate: '2024-01-01',
    },
    relatedTools: ['marks-percentage-calculator', 'grade-calculator', 'exam-score-calculator'],
  },
  {
    id: 'ssc-chsl-score-calculator',
    slug: 'ssc-chsl-score-calculator',
    category: 'exams',
    title: 'SSC CHSL Score Calculator',
    shortDescription: 'Calculate your SSC CHSL Tier 1 score with negative marking.',
    keywords: ['ssc chsl score', 'ssc chsl marks', 'ssc chsl calculator', 'ssc chsl negative marking'],
    aliases: ['ssc chsl tier 1 score calculator'],
    computation: 'sscChslScore',
    needsClient: true,
    commercialIntent: 'low',
    formula: 'Score = (Correct × 2) − (Incorrect × 0.5)',
    explanation: 'This calculator computes your estimated SSC CHSL Tier 1 score. Each correct answer awards 2 marks, and each wrong answer deducts 0.5 marks.',
    examples: [{ title: 'Score estimate', inputs: [{ label: 'Correct: 70' }, { label: 'Incorrect: 8' }], result: 'Score = 140 − 4 = 136' }],
    assumptions: 'Based on SSC CHSL Tier 1 exam pattern. Each question is 2 marks with 0.5 negative marking per wrong answer. Verify for your exam session.',
    source: {
      name: 'Staff Selection Commission',
      url: 'https://ssc.nic.in',
      effectiveDate: '2024-01-01',
    },
    relatedTools: ['ssc-cgl-score-calculator', 'marks-percentage-calculator', 'grade-calculator'],
  },
];

/** Get a tool by slug */
export function getTool(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

/** Get all tools in a category */
export function getToolsByCategory(category: Category): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

/** Get all categories that have tools */
export function getActiveCategories(): Category[] {
  const cats = new Set(tools.map((t) => t.category));
  return Array.from(cats) as Category[];
}

/** Search tools by query */
export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return tools
    .filter((t) => {
      const haystack = [
        t.title,
        t.shortDescription,
        ...(t.keywords || []),
        ...(t.aliases || []),
        t.category,
      ]
        .join(' ')
        .toLowerCase();
      return haystack.includes(q);
    })
    .slice(0, 10);
}

/** Get related tools by slugs */
export function getRelatedTools(slugs: string[]): ToolDefinition[] {
  return slugs
    .map((s) => getTool(s))
    .filter((t): t is ToolDefinition => t !== undefined);
}

/** Get popular tools for homepage */
export function getPopularTools(): ToolDefinition[] {
  const popularSlugs = [
    'percentage-calculator',
    'age-calculator',
    'emi-calculator',
    'cgpa-calculator',
    'json-formatter',
    'days-between-dates',
    'salary-increment-calculator',
    'unit-conversion',
    'gst-calculator',
    'discount-calculator',
  ];
  return popularSlugs
    .map((s) => getTool(s))
    .filter((t): t is ToolDefinition => t !== undefined);
}

/** Validate all tools have required metadata */
export function validateTools(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  const slugs = new Set<string>();

  for (const tool of tools) {
    if (!tool.id) errors.push(`Tool missing id`);
    if (!tool.slug) errors.push(`Tool "${tool.id}" missing slug`);
    if (slugs.has(tool.slug)) errors.push(`Duplicate slug: ${tool.slug}`);
    slugs.add(tool.slug);
    if (!tool.title) errors.push(`Tool "${tool.id}" missing title`);
    if (!tool.shortDescription) errors.push(`Tool "${tool.id}" missing shortDescription`);
    if (!tool.category) errors.push(`Tool "${tool.id}" missing category`);
    if (!tool.computation) errors.push(`Tool "${tool.id}" missing computation`);
    if (tool.keywords.length === 0) errors.push(`Tool "${tool.id}" has no keywords`);
    if (!tool.formula) errors.push(`Tool "${tool.id}" missing formula`);
    if (!tool.explanation) errors.push(`Tool "${tool.id}" missing explanation`);
    if (tool.examples.length === 0) errors.push(`Tool "${tool.id}" has no examples`);
    if (tool.relatedTools.length === 0) errors.push(`Tool "${tool.id}" has no related tools`);

    // Check related tools exist
    for (const relatedSlug of tool.relatedTools) {
      if (!getTool(relatedSlug)) {
        errors.push(`Tool "${tool.id}" references non-existent related tool: ${relatedSlug}`);
      }
    }
  }

  return { valid: errors.length === 0, errors };
}
